"""Blind, causal rule-discovery utilities for replay candidates."""

from .experiment import (
    DISCOVERY_FEATURE_ALLOWLIST,
    MAX_RESEARCH_SECONDS,
    OutcomeConfig,
    apply_rule,
    build_blind_dataset,
    build_feature_dossier,
    build_market_context,
    build_reviewer_market_context,
    evaluate_candidate_path,
    evaluate_frozen_rule,
    freeze_rule_artifact,
    load_replay_candidates,
    point_in_time_market_features,
    purged_chronological_holdout,
    restrict_to_mature_outcome_quarters,
    run_research_command,
    validate_rule_artifact,
    validate_rule_support,
)

__all__ = [
    "DISCOVERY_FEATURE_ALLOWLIST",
    "MAX_RESEARCH_SECONDS",
    "OutcomeConfig",
    "apply_rule",
    "build_blind_dataset",
    "build_feature_dossier",
    "build_market_context",
    "build_reviewer_market_context",
    "evaluate_candidate_path",
    "evaluate_frozen_rule",
    "freeze_rule_artifact",
    "load_replay_candidates",
    "point_in_time_market_features",
    "purged_chronological_holdout",
    "restrict_to_mature_outcome_quarters",
    "run_research_command",
    "validate_rule_artifact",
    "validate_rule_support",
]
