"""Backward-compatible imports for the audited EPS PIT provider stack."""

from eps_pit.providers.composite_provider import SECYahooEPSProvider
from eps_pit.providers.pit_provider import (  # noqa: F401
    DEFAULT_CACHE_DIR,
    DEFAULT_CACHE_TTL_SECONDS,
    NO_PRIOR_YEAR_QUARTER,
    NO_QUARTERLY_EPS,
    NO_VERIFIED_YAHOO_RELEASE_DATE,
    PRIOR_YEAR_EPS_ZERO,
    PROVIDER_ERROR,
    SECProvider,
    TTLJSONCache,
    YahooFundamentalsProvider,
    calculate_latest_eps_yoy,
    calculate_latest_eps_yoy_diagnostic,
    date10,
    duration_days,
    is_standalone_quarter,
    normalize_symbol,
    safe_float,
    select_visible_quarters,
)

__all__ = [
    "DEFAULT_CACHE_DIR",
    "DEFAULT_CACHE_TTL_SECONDS",
    "NO_PRIOR_YEAR_QUARTER",
    "NO_QUARTERLY_EPS",
    "NO_VERIFIED_YAHOO_RELEASE_DATE",
    "PRIOR_YEAR_EPS_ZERO",
    "PROVIDER_ERROR",
    "SECProvider",
    "SECYahooEPSProvider",
    "TTLJSONCache",
    "YahooFundamentalsProvider",
    "calculate_latest_eps_yoy",
    "calculate_latest_eps_yoy_diagnostic",
    "date10",
    "duration_days",
    "is_standalone_quarter",
    "normalize_symbol",
    "safe_float",
    "select_visible_quarters",
]
